name: Build macOS App

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build app with py2app
        run: |
          python3 setup.py py2app

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: CarnErg-macOS
          path: dist/
